version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container_mastering
    environment:
      POSTGRES_USER: user_calebe
      POSTGRES_PASSWORD: pass_calebe
      POSTGRES_DB: db_lebe
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: